[package]
name = "CountingBot"
version = "0.1.0"
authors = ["Sam"]
edition = "2018"

[dependencies]
env_logger = "0.6.0"
kankyo = "0.2.0"
log = "0.4.6"

[dependencies.serenity]
features = ["cache", "framework", "standard_framework"]